### PR TITLE
feat: Add deploy script

### PR DESCRIPTION
**Pull request by dosht**
TODO:

- [x] Split k8s.yaml to multiple file
- [x] Support local deployment (e.g. to Minikube)
- [x] Fix configMapRef and test

### CODE REVIEW

**Comment by dosht** [comment]
I get an error related to configMapRef when I try to build with Kustomize:

```
kustomize build local
2019/11/09 23:08:46 nil value at `configMapRef.name` ignored in mutation attempt
2019/11/09 23:08:46 nil value at `configMapRef.name` ignored in mutation attempt
2019/11/09 23:08:46 nil value at `configMapRef.name` ignored in mutation attempt
```

**Comment by mgharbik** [comment]
@dosht somehow `configMapRef.name` needs 2 tabs indent, I honestly don't know why.

By the way `envFrom` is a redundant key we can get rid of it and use arrays.

**Review by mgharbik — COMMENTED** [review]
@dosht I have some proposals:

- What do you think to create a new `ConfigMap` like `masajid-config` with variables from the app like: `RAILS_SERVE_STATIC_FILES`, `PROJECT_HOSTNAME`, `SUPER_ADMIN_EMAIL`, `ADMIN_SENDER_EMAIL`, `ADMIN_NOTIFICATION_EMAILS`, `REDIS_URL`.

- Jobs is another concept in kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/, I would rename it `cron_jobs`.

**Review by EslamElHusseiny — CHANGES_REQUESTED** [review]
Let's maintain a consistent yaml files with the same order of `apiVersion`, `kind`, `meta` and `specs`

**Comment by dosht** [comment]
> Let's maintain a consistent yaml files with the same order of `apiVersion`, `kind`, `meta` and `specs`

@EslamElHusseiny I couldn't understand from the documentation which version we should use.

**Comment by EslamElHusseiny** [comment]
@dosht which version?

**Comment by dosht** [comment]
I understood wrong. You only talked about ordering. I thought you want also to have the same `apiVersion` for all resources. 👍

**Comment by dosht** [comment]
@EslamElHusseiny  I updated the PR. Please recheck.

**Comment by EslamElHusseiny** [comment]
@dosht base/masajid/deployment.yaml is missing

**Comment by dosht** [comment]
@EslamElHusseiny Done

**Review by EslamElHusseiny — APPROVED** [review]

**Pull request merged**
